### ISSUE TITLE
json2mask.py module 'labelme.utils' has no attribute 'draw_label'

### ISSUE THREAD

**Issue by deepseek** [guchengxi1994/mask2json#2]
@guchengxi1994 

when runing json2mask.py using my sample [data.zip](https://github.com/guchengxi1994/mask2json/files/4802659/data.zip)

```
(d2) home@home-desktop:~/0/vision_data_tools-master/data$ python json2mask.py 
[WARNING] shape:labelme_shapes_to_label:80 - labelme_shapes_to_label is deprecated, so please use shapes_to_label.
Traceback (most recent call last):
  File "json2mask.py", line 95, in <module>
    singleFile('./5.json')
  File "json2mask.py", line 67, in singleFile
    lbl_viz = utils.draw_label(lbl, img, captions)
AttributeError: module 'labelme.utils' has no attribute 'draw_label'
```

**Comment by guchengxi1994** [comment]
the reason is the newest labelme deletes the draw.py .



here is my solution ,you can have a try:

1) you copy 'https://github.com/guchengxi1994/mask2json/blob/master/backup/draw.py' to your  labelme path (mine is '../anaconda/Lib/site-packages/labelme/utils ' )

2) add these codes in __init__.py
from .draw import label_colormap
from .draw import _validate_colormap
from .draw import label2rgb
from .draw import draw_label
from .draw import draw_instances

**Comment by deepseek** [comment]
which version of labelme is compatible with your script?
https://pypi.org/project/labelme/#history
pip install labelme==??

**Comment by deepseek** [comment]
now i get error
```
(labelme) home@home-desktop:~/0/mask2json-master/data$ python mask2json.py 
Traceback (most recent call last):
  File "mask2json.py", line 11, in <module>
    from utils import getShape
ModuleNotFoundError: No module named 'utils'

```
