### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by Rock-L21** [guchengxi1994/mask2json#44]
I always get an error when I use **pip install -r requests.txt**, what is the version of Python you are using?

**Comment by guchengxi1994** [comment]
@Rock-L21  I was using python3.8 and anaconda . Besides, if you got an error when installing ```PyYaml```, you can try
**pip install -r requirements.txt --ignore-installed**

**Comment by Rock-L21** [comment]
@guchengxi1994  Thanks a lot.

**Comment by guchengxi1994** [comment]
@Rock-L21  I tested on a new conda env, and when I install **scikit-image** and **matplotlib** ,it went error.  If you are facing with the same error, you can remove these two package in the requirements.txt, and install them later when **numpy** is installed.

**Comment by Rock-L21** [comment]
Hello, after I installed Python3.8, all the packages have been installed, but an error occurred when installing the package version you requested. Can you tell me all the package versions in your current virtual environment.

**Comment by Rock-L21** [comment]
Can the mask2json.py in your repository generate the json file (Y000007.json) in the link below based on the mask.

**Comment by Rock-L21** [comment]
https://drive.google.com/drive/folders/13d1uqE42UpiyPAyx3NiaNwhEdifWxu3j?usp=sharing

**Comment by guchengxi1994** [comment]
@Rock-L21  I wrote a script.
```python
import numpy as np
from skimage import io 

imgpath = "D:\\github_repo\\mask2json\\test\\000000031_Singlechannelgrayscale.png"
img = io.imread(imgpath)

a = np.unique(img)
print(a)
img[img==85] = 1
img[img==170] = 2
img[img==255] = 3
io.imsave("D:\\github_repo\\mask2json\\test\\mask.png",img)
```

I think this file is your **mask** file, however, your classes ids are [0 85 170 255] , which cannot be used in my script.（see utils/methods/get_multi_shapes.py  row 234）,so I change your class id to [0 1 2 3]

then , run these code:

```python
from convertmask.utils.methods import get_multi_shapes

imgPath = 'D:\\github_repo\\mask2json\\test\\000000031_Groundtruth.png'
maskPath = 'D:\\github_repo\\mask2json\\test\\mask.png'
savePath = 'D:\\github_repo\\mask2json\\static\\multi_objs_json\\2022318\\'
yamlPath = 'D:\\github_repo\\mask2json\\static\\multi_objs_json\\info1.yaml'
get_multi_shapes.getMultiShapes(imgPath, maskPath, savePath, yamlPath)  # with yaml
```

then the json file is created in ```D:\\github_repo\\mask2json\\static\\multi_objs_json\\2022318\\```

and i open the json file in labelme, got this

![image](https://user-images.githubusercontent.com/33513462/158984543-7a06f293-73ef-4315-9dbc-78aa6ff5c05c.png)

because i dont know your classes, so i replace all class names with "class1","class2"...

you can change the ***info1.yaml*** with your classnames and ids, eg.

```yaml
label_names:
  _background_: 0
  class1: 1
  class2: 2
  class3: 3
```

**Comment by Rock-L21** [comment]
Following your script, the problem has been solved, thanks again.
