### ISSUE TITLE
test_imgAug There is a problem with data enhancement

### ISSUE THREAD

**Issue by monkeycc** [guchengxi1994/mask2json#55]
![100](https://user-images.githubusercontent.com/6490927/177028294-74db7459-7ff3-4c31-8360-61940334974b.jpg)

[100.zip](https://github.com/guchengxi1994/mask2json/files/9034215/100.zip)

100_noise Labels  normal
Other labels are abnormal

**Comment by guchengxi1994** [comment]
I am not sure, but I notice your label and yaml files maybe  incorrect.
```yaml
label_names:
  DA: 0
  XIAO: 1
  ZHONG: 2
```
first, if you want to label `DA` out, you should not mark `DA` as 0, because 0 means background(which will not be detected).

second, I notice that your labels are overlapped, which may cause some problems when testing your models. (such as something is A but it is B also)

Maybe use
```python
imgFlip(imgPath, labelPath,labelFile=yamlPath)
imgNoise(imgPath, labelPath,labelFile=yamlPath)
imgRotation(imgPath, labelPath,labelFile=yamlPath)
imgTranslation(imgPath, labelPath,labelFile=yamlPath)
imgZoom(imgPath, labelPath, 1.2,labelFile=yamlPath)
```

or 

```python
aug_labelme(imgPath, labelPath,yamlFilePath=yamlPath,augs=['flip','noise'])
```

for another test?
